# Generated by Django 4.2.4 on 2023-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodImage',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='food',
            name='foodName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='food',
            name='foodPrice',
            field=models.IntegerField(default=0),
        ),
    ]
