# Generated by Django 4.2.4 on 2023-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_food_foodimage_food_foodname_food_foodprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='likesCount',
            field=models.IntegerField(default=10),
        ),
    ]
