# Generated by Django 4.2.4 on 2023-08-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_food_likescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='foodImage',
            field=models.CharField(default='', max_length=30),
        ),
    ]
