# Generated by Django 4.2.4 on 2023-08-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=11)),
                ('subject', models.CharField(default='', max_length=100)),
                ('text', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
