# Generated by Django 4.2.4 on 2023-08-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_commentabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodImage',
            field=models.ImageField(upload_to='foodImages'),
        ),
    ]
