# Generated by Django 4.2.4 on 2023-08-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_food_isexist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home_app.food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='showing',
            field=models.BooleanField(default=False),
        ),
    ]
