# Generated by Django 4.2.4 on 2023-08-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='confirmPassword',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='signin',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
