# Generated by Django 4.2.4 on 2023-09-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfFood', models.CharField(default='', max_length=50)),
                ('countOfFood', models.IntegerField(default=0)),
                ('priceOfFood', models.IntegerField(default=0)),
                ('nameOfCostumer', models.CharField(default='', max_length=50)),
                ('phoneOfCostumer', models.CharField(default='', max_length=11)),
                ('dateOfReceive', models.CharField(default='', max_length=11)),
                ('forDinnerOrLaunch', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
